export const routes = {
  home: "/",
  login: "/login",
  sign_up: "/sign-up",
  baby_clothes: "/baby-clothes",
  baby_sleepingwear: "/sleeping-wear",
  baby_swimwear: "/swim-wear",
  girls_dress: "/girls-dresses",
  girls_top: "/girls-tops",
  girls_acc: "/girls-acc",
  boys_top: "/boys-top",
  boys_bottom: "/boys-bottom",
  boys_activewear: "/boys-activewear",
  swim_diaper: "/swim-diapers",
  reusable_diaper: "/reusable-diaper",
  baby_powder: "/baby-powder",
  baby_cream: "/baby-cream",
  fashion_dolls: "fashion-dolls",
  baby_parms: "/baby-parms",
  action_toy: "/action-toys",
  sale_items: "/sale-items",
};
